#!/bin/sh

echo "111111111111111111111111"
echo "MANIFEST=${MANIFEST}" 
echo "BRANCH=${BRANCH}"
echo "MACHINE_NAME=${MACHINE_NAME}" 
echo "TARGET_IMAGE=${TARGET_IMAGE}" 
echo "BUILD_PARAM=${BUILD_PARAM}" 
echo "REPOURL=${REPOURL}" 
echo "USE_SSTATE_CACHE=${USE_SSTATE_CACHE}" 
echo "DISTRO_FEATURES=${DISTRO_FEATURES}" 
echo "PATCHLIST=${PATCHLIST}"

echo "shell Branch is: ${BRANCH_NAME}"
exit 0